# Generated by Django 2.1.5 on 2019-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntiadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ews_submission',
            name='helper',
            field=models.TextField(default=' '),
        ),
    ]
