# Generated by Django 2.1.5 on 2019-05-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('ntiadmin', '0002_ews_submission_helper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseEnrolls',
            new_name='CourseEnroll',
        ),
        migrations.RenameModel(
            old_name='EWS_submission',
            new_name='EWSSubmission',
        ),
    ]
