# Generated by Django 2.1.5 on 2019-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntiadmin', '0003_auto_20190528_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ewssubmission',
            old_name='ews',
            new_name='ewscolor',
        ),
        migrations.RenameField(
            model_name='ewssubmission',
            old_name='helper',
            new_name='ewshelper',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'ALLA'), (2, 'EL16'), (3, 'EL17'), (4, 'EL18'), (5, 'EL19'), (6, 'EL20'), (7, 'TEK16'), (8, 'TEK17'), (9, 'TEK18'), (10, 'TEK19'), (11, 'TEK20'), (12, 'DIG16'), (13, 'DIG17'), (14, 'DIG18'), (15, 'DIG19'), (16, 'DIG20'), (17, 'FYRA')], default=0),
        ),
    ]
